---
title: "dxf_reader"
author: "Scott McKean"
date: "4/23/2019"
output: html_document
---

Read in a .dxf file from acrobat using rGDAL

```{r setup, include=FALSE}
dxf_file <- 'munge/vertedges.dxf'

read_process_dxf <- function(dxf_file, scanline_direction = 'horiz'){
  sf_df <- readOGR(dsn = dxf_file) %>%
    st_as_sf(ogr)
  
  if (!scanline_direction %in% c('horiz','vert')){
    warning('Scanline direction not specified as horizontal or vertical, setting to horizontal')
    scanline_direction = 'horiz'
  }
  
  
}
  
  if (str_detect(file,'horiz')) {
    # vertical line
    x = seq(10,1000, by = 10)
    coord <- x
    set = 'horiz'
    col <- 'Y'
    f_linestring <- function(x){
      st_linestring(matrix(c(x,x,0,-1000), ncol = 2), dim = 'XY')
    }
    linestrings <- lapply(x,f_linestring) %>% st_sfc() %>% st_sf()
  } else {
    # horizontal line
    y = seq(10,1000, by = 10)
    coord <- y
    set = 'vert'
    col <- 'X'
    f_linestring <- function(y){
      st_linestring(matrix(c(0,1000,-y,-y), ncol = 2), dim = 'XY')
    }
    linestrings <- lapply(y,f_linestring) %>% st_sfc() %>% st_sf()
  }
```

# Read file

- We can export illustrator layers using .dxf files, which can be read by rgdal quite easily.

```{r}
# Read DXF file with rgdal
shapefiles <- list.files(pattern = 'AC1_01.*\\.dxf$', recursive = TRUE)
scanline_df = data.frame()
fracture_df = data.frame()
window_df = data.frame()

for (file in shapefiles){
  # get window info
  window <- str_extract(file,"AC1_.*/")
  w_outcrop <- str_sub(window,1,3)
  w_meas <- str_sub(window,5,6)
  
  ogr <- readOGR(dsn = file)
  
  sf_df <- st_as_sf(ogr)
  
  if (str_detect(file,'horiz')) {
    # vertical line
    x = seq(10,1000, by = 10)
    coord <- x
    set = 'horiz'
    col <- 'Y'
    f_linestring <- function(x){
      st_linestring(matrix(c(x,x,0,-1000), ncol = 2), dim = 'XY')
    }
    linestrings <- lapply(x,f_linestring) %>% st_sfc() %>% st_sf()
  } else {
    # horizontal line
    y = seq(10,1000, by = 10)
    coord <- y
    set = 'vert'
    col <- 'X'
    f_linestring <- function(y){
      st_linestring(matrix(c(0,1000,-y,-y), ncol = 2), dim = 'XY')
    }
    linestrings <- lapply(y,f_linestring) %>% st_sfc() %>% st_sf()
  }
  
  for (i in 1:nrow(linestrings)){
  
    linestring <- linestrings[i,]
    
    intersects <- st_intersection(st_geometry(linestring),
                                  st_geometry(sf_df)) %>%
      st_coordinates()
      
    line_length <- st_length(linestring)
    
    if (nrow(intersects) != 0) {
      frac_spacing <- intersects[,col] %>% 
        diff() %>% 
        abs() %>% 
        mean()
    } else {
      frac_spacing <- NA
    }
    
    frac_count <- intersects %>% nrow()
    
    P10 <- frac_count/line_length*1000
      
    out <- data.frame('outcrop' = w_outcrop,
                      'window' = w_meas,
                      'set' = set,
                      'coord' = coord[i],
                      'line_length' = line_length,
                      'frac_spacing' = frac_spacing,
                      'frac_count' = frac_count, 
                      'P10' = P10)
    
    scanline_df <- rbind(scanline_df,out)
  }
  
  # get angles
  coords <- st_cast(sf_df, to = 'MULTIPOINT') %>% st_coordinates()
  ind <- seq(1,nrow(coords), by = 2)
  angles <- atan2((coords[ind+1,2]-coords[ind,2]),(coords[ind+1,1]-coords[ind,1]))
  
  # get centres
  centroid <- st_centroid(sf_df) %>% st_coordinates()
  
  fracture_df <- data.frame('outcrop' = w_outcrop, 'window' = w_meas, 'set' = set, 
                            'length' = st_length(sf_df), 'angle' = angles, 
                            'x_centre' = centroid[,1], 'y_centre' = -centroid[,2])  %>%
    rbind(fracture_df,.)
  
  window_df <- data.frame('outcrop' = w_outcrop, 'window' = w_meas, 'set' = set, 
                          'P21' = st_length(sf_df ) %>% sum() / 1000, 'P20' = nrow(sf_df)) %>%
    rbind(window_df,.)
}

write.csv(scanline_df, paste(w_outcrop,'scanlines.csv', sep = '_'))
write.csv(fracture_df, paste(w_outcrop,'fractures.csv', sep = '_'))
write.csv(window_df, paste(w_outcrop,'window.csv', sep = '_'))
getwd()
```

```{r}
# show log normal distribution of fracture lengths
ggplot(fracture_df) +
  geom_histogram(aes(x=log10(length)), bins = 50) +
  ylab('Fracture Count') +
  xlab('Log Length (mm)') +
  ggsave('AC_01_fracture_length.jpg', dpi = 600, width = 4, height = 4)

# show bimodal distribution of fracture sets + random sets
ggplot(fracture_df) +
  geom_histogram(aes(x=angle*180/pi), bins = 50) +
  ylab('Fracture Count') +
  xlab('Angle (Degrees)') +
  ggsave('AC_01_fracture_angle.jpg', dpi = 600, width = 4, height = 4)

# fracture intensity vs depth
ggplot(scanline_df %>% filter(set == 'vert')) +
  geom_path(aes(y = coord, x = frac_count)) + 
  geom_point(aes(y = coord, x = frac_count)) + 
  theme_minimal() +
  ylab('Depth (mm)') +
  xlab('Fracture Intensity (P10, fractures/m)') +
  ggsave('AC_01_vert_frac_intensity.jpg', dpi = 600, width = 4, height = 8)
```
